#include "lists.h"

namespace global::lists {
	scroll_struct<uint32_t> g_timers[] = {
		{ localization("Unlocked", true), 0 },
		{ localization("100ms", true), 100 },
		{ localization("250ms", true), 250 },
		{ localization("500ms", true), 500 },
		{ localization("750ms", true), 750 },
		{ localization("1s", true), 1000 },
		{ localization("2.5s", true), 2500 },
		{ localization("5s", true), 5000 },
		{ localization("10s", true), 10000 },
		{ localization("15s", true), 15000 },
	};

	scroll_struct<float> g_distances[] = {
		{ localization("Unlocked", true), 99999.f },
		{ localization("50m", true), 50.f },
		{ localization("100m", true), 100.f },
		{ localization("200m", true), 200.f },
		{ localization("250m", true), 250.f },
		{ localization("300m", true), 300.f },
		{ localization("400m", true), 400.f },
		{ localization("500m", true), 500.f }
	};

	scroll_struct<uint32_t> g_ped_model_popular[] = {
		{ localization("Alien", true), 0x64611296 },
		{ localization("Astronaut", true), 0xE7B31432 },
		{ localization("Playboy (Naked)", true), 0x4498DDE },
		{ localization("Hooker", true), 0x28ABF95 },
		{ localization("Pogo", true), 0xDC59940D },
		{ localization("Stripper", true), 0x52580019 },
		{ localization("Swat", true), 0x8D8F1B10 },
		{ localization("Topless", true), 0x9CF26183 },
		{ localization("Zombie", true), 0xAC4B4506 },
	};

	scroll_struct<uint32_t> g_ped_model_story[] = {
		{ localization("Michael", true), 0xD7114C9 },
		{ localization("Franklin", true), 0x9B22DBAF },
		{ localization("Trevor", true), 0x9B810FA2 },
		{ localization("Amanda", true), 0x6D1E15F7 },
		{ localization("Ashley", true), 0x7EF440DB },
		{ localization("Brad", true), 0xBDBB4922 },
		{ localization("Chef", true), 0x49EADBF6 },
		{ localization("Chris Formage", true), 0x286E54A7 },
		{ localization("Clag", true), 0x6CCFE08A },
		{ localization("Cletus", true), 0xE6631195 },
		{ localization("Dave Norton", true), 0x15CD4C33 },
		{ localization("Denise", true), 0x820B33BD },
		{ localization("Fabien", true), 0xD090C350 },
		{ localization("Floyd", true), 0xB1B196B2 },
		{ localization("Jay Norris", true), 0x7A32EE74 },
		{ localization("Jimmy", true), 0x570462B9 },
		{ localization("Lamar", true), 0x65B93076 },
		{ localization("Lazlow", true), 0xDFE443E5 },
		{ localization("Lester", true), 0x4DA6E849 },
		{ localization("Mrs Phillips", true), 0x3862EEA8 },
		{ localization("Stretch", true), 0x36984358 },
		{ localization("Tao Cheng", true), 0xDC5C5EA5 },
		{ localization("Tennis Coach", true), 0xA23B5F57 },
		{ localization("Tracy", true), 0xDE352A35 },
		{ localization("Wade", true), 0x92991B72 }
	};

	scroll_struct<uint32_t> g_ped_model_animal[] = {
		{ localization("Boar", true), 0xCE5FF074 },
		{ localization("Chimp", true), 0xA8683715 },
		{ localization("Chop", true), 0x14EC17EA },
		{ localization("Cow", true), 0xFCFA9E1E },
		{ localization("Coyote", true), 0x644AC75E },
		{ localization("Crow", true), 0x18012A9F },
		{ localization("Deer", true), 0xD86B5A95 },
		{ localization("Fish", true), 0x2FD800B7 },
		{ localization("Chicken Hawk", true), 0xAAB71F62 },
		{ localization("Hen", true), 0x6AF51FAF },
		{ localization("Husky", true), 0x4E8F95A2 },
		{ localization("Mountain Lion", true), 0x1250D7BA },
		{ localization("Pig", true), 0xB11BAB56 },
		{ localization("Pigeon", true), 0x6A20728 },
		{ localization("Retriever", true), 0x349F33E1 },
		{ localization("Rhesus", true), 0xC2D06F53 },
		{ localization("Rottweiler", true), 0x9563221D },
		{ localization("Seagull", true), 0xD3939DFD },
		{ localization("Tiger Shark", true), 0x6C3F072 },
		{ localization("Shepherd", true), 0x431FC24C },
	};

	scroll_struct<uint32_t> g_ped_model_emergency[] = {
		{ localization("Black Ops", true), 0xB3F3EE34 },
		{ localization("Chem Security", true), 0x2EFEAFD5 },
		{ localization("City Cop", true), 0x5E3DA4A4 },
		{ localization("County Cop", true), 0x9AB35F63 },
		{ localization("Fireman", true), 0xB6B1EDA8 },
		{ localization("Security Guard", true), 0x709220C7 },
		{ localization("Highway Cop", true), 0x739B1EF5 },
		{ localization("Lifeguard", true), 0xB4A6862 },
		{ localization("Marine", true), 0x72C0CAD2 },
		{ localization("Marine (Senior)", true), 0xF0259D83 },
		{ localization("Paramedic", true), 0xB353629E },
		{ localization("Ranger", true), 0xEF7135AE },
		{ localization("Prison Guard", true), 0x56C96FC6 },
		{ localization("Security Guard", true), 0xD768B228 },
		{ localization("Sheriff", true), 0xB144F9B9 },
		{ localization("Snow Cop", true), 0x1AE8BB58 },
	};

	scroll_struct<uint32_t> g_ped_model_role[] = {
		{ localization("Bouncer", true), 0x9FD4292D },
		{ localization("Bride", true), 0x6162EC47 },
		{ localization("Pest Control", true), 0x48114518 },
		{ localization("Doctor", true), 0xD47303AC },
		{ localization("Factory Worker", true), 0x4163A158 },
		{ localization("Garbage Man", true), 0xEE75A00F },
		{ localization("Groom", true), 0xFECE8B85 },
		{ localization("Hunter", true), 0xCE1324DE },
		{ localization("Jesus", true), 0xCE2CB751 },
		{ localization("Mime", true), 0x3CDCA742 },
		{ localization("Priest", true), 0x6437E77D },
		{ localization("Prisoner", true), 0xB1BB9B59 },
		{ localization("Scientist", true), 0x4117D39B },
		{ localization("Spy", true), 0x5B81D86C },
	};

	scroll_struct<uint32_t> g_ped_model_ambient[] = {
		{ localization("Body Builder", true), 0xDA116E7E },
		{ localization("Nonce", true), 0x7DC3908F },
		{ localization("Guido", true), 0xC6B49A2F },
		{ localization("Statue", true), 0x795AC7A8 },
		{ localization("Mani", true), 0xC8BB1E52 },
		{ localization("Griff", true), 0xC454BCBB },
	};

	scroll_struct<uint32_t> g_ped_model_misc[] = {
		{ localization("Dead Hooker", true), 0x73DEA88B },
		{ localization("Imporage", true), 0x348065F5 },
		{ localization("Marston", true), 0x38430167 },
		{ localization("Misty", true), 0xD128FF9D },
		{ localization("Niko", true), 0xEEDACFC9 },
	};

	scroll_struct<int> g_ped_bones[] = {
		{ localization("Head", true), 31086 },
		{ localization("Neck", true), 39317 },
		{ localization("Chest", true), 24818 },
		{ localization("Right Hand", true), 57005 }, // 28422
		{ localization("Left Hand", true), 18905 }, // 36029
		{ localization("Right Foot", true), 52301 }, // 6286
		{ localization("Left Foot", true), 14201 },
		{ localization("Right Calf", true), 36864 },
		{ localization("Left Calf", true), 63931 },
		{ localization("Right Forearm", true), 28252 },
		{ localization("Left Forearm", true), 61163 },
		{ localization("Right Upper Arm", true), 40269 },
		{ localization("Left Upper Arm", true), 45509 }
	};

	scroll_struct<const char*> g_vehicle_bones[] = {
		{ localization("Front: Left Wheel", true), "wheel_lf" },
		{ localization("Front: Right Wheel", true), "wheel_rf" },
		{ localization("Rear: Left Wheel", true), "wheel_lr" },
		{ localization("Rear: Right Wheel", true), "wheel_rr" },
		{ localization("Left: Tail Light", true), "taillight_l" },
		{ localization("Left: Headlight", true), "headlight_l" },
		{ localization("Right: Tail Light", true), "taillight_r" },
		{ localization("Right: Headlight", true), "headlight_r" },
		{ localization("Numberplate", true), "numberplate" },
		{ localization("Exhaust", true), "exhaust" }
	};

	scroll_struct<particle> g_particles[] = {
		{ localization("Purple Cloud 1", true), { "scr_rcbarry2", "scr_clown_appears", false } },
		{ localization("Purple Cloud 2", true), { "scr_rcbarry2", "scr_clown_death", false } },
		{ localization("Purple Cloud 3", true), { "scr_rcbarry2", "scr_exp_clown", false } },
		{ localization("Firework Starburst", true), { "scr_indep_fireworks", "scr_indep_firework_starburst", false } },
		{ localization("Firework Fountain", true), { "scr_indep_fireworks", "scr_indep_firework_fountain", false } },
		{ localization("Firework Shotburst", true), { "scr_indep_fireworks", "scr_indep_firework_shotburst", false } },
		{ localization("Xmas Firework Burst", true), { "proj_xmas_firework", "scr_firework_xmas_spiral_burst_rgw", false } },
		{ localization("Teleport", true), { "scr_rcbarry1", "scr_alien_teleport", false } },
		{ localization("Disintegration", true), { "scr_rcbarry1", "scr_alien_disintegrate", false } },
		{ localization("Drip", true), { "scr_agencyheist", "scr_fbi_mop_drips", false } },
		{ localization("Flower Jet", true), { "scr_rcbarry2", "scr_clown_bul", false } },
		{ localization("Flash", true), { "scr_rcpaparazzo1", "scr_rcpap1_camera", false } },
		{ localization("Blue Flash", true), { "scr_rcbarry1", "scr_alien_impact_bul", false } },
		{ localization("Burnout", true), { "scr_recartheft", "scr_wheel_burnout", false } },
		{ localization("Splash", true), { "scr_trevor1", "scr_trev1_trailer_splash", false } },
		{ localization("Blood", true), { "scr_solomon3", "scr_trev4_747_blood_impact", false } },
		{ localization("Sparks", true), { "scr_family4", "scr_fam4_trailer_sparks", false } },
		{ localization("Shock", true), { "scr_trevor1", "scr_trev1_trailer_boosh", false } },
		{ localization("Money Cloud", true), { "scr_ornate_heist", "scr_heist_ornate_banknotes", false } },
		{ localization("Tire Smoke", true), { "scr_carsteal4", "scr_carsteal4_wheel_burnout", false } },
		{ localization("Clouds", true), { "wpn_projectile", "proj_missile_trail", true } },
		{ localization("Golf Trail", true), { "scr_minigamegolf", "scr_golf_ball_trail", true } },
		{ localization("Tennis Trail", true), { "scr_minigametennis", "scr_tennis_ball_trail", true } },
		{ localization("Water Trail", true), { "core", "trail_splash_water", true } },
		{ localization("Parachute Trail", true), { "core", "ped_parachute_trail", true } },
		{ localization("Flare Trail", true), { "core", "proj_flare_trail", true } },
		{ localization("Blood Trail", true), { "core", "trail_splash_blood", true } },
		{ localization("Grenade Trail", true), { "wpn_projectile", "proj_grenade_trail", true } },
		{ localization("Flaregun Trail", true), { "wpn_projectile", "proj_flare_trail", true } },
	};

	scroll_struct<uint32_t> g_weapons[] = {
		{ localization("Pistol", true), 0x1b06d571 },
		{ localization("Pistol Mk II", true), 0xbfe256d4 },
		{ localization("Combat Pistol", true), 0x5ef9fec4 },
		{ localization("AP Pistol", true), 0x22d8fe39 },
		{ localization("Stun Gun", true), 0x3656c8c1 },
		{ localization("Pistol .50", true), 0x99aeeb3b },
		{ localization("SNS Pistol", true), 0xbfd21232 },
		{ localization("SNS Pistol Mk II", true), 0x88374054 },
		{ localization("Heavy Pistol", true), 0xd205520e },
		{ localization("Vintage Pistol", true), 0x83839c4 },
		{ localization("Flare Gun", true), 0x47757124 },
		{ localization("Marksman Pistol", true), 0xdc4db296 },
		{ localization("Heavy Revolver", true), 0xc1b3c3d1 },
		{ localization("Heavy Revolver Mk II", true), 0xcb96392f },
		{ localization("Double Action Revolver", true), 0x97ea20b8 },
		{ localization("Up-n-Atomizer", true), 0xaf3696a1 },
		{ localization("Ceramic Pistol", true), 0x2b5ef5ec },
		{ localization("Navy Revolver", true), 0x917f6c8c },
		{ localization("Gadget Pistol", true), 0x57a4368c },

		{ localization("Micro SMG", true), 0x13532244 },
		{ localization("SMG", true), 0x2be6766b },
		{ localization("SMG Mk II", true), 0x78a97cd0 },
		{ localization("Assault SMG", true), 0xefe7e2df },
		{ localization("Combat PDW", true), 0xa3d4d34 },
		{ localization("Machine Pistol", true), 0xdb1aa450 },
		{ localization("Mini SMG", true), 0xbd248b55 },
		{ localization("Unholy Hellbringer", true), 0x476bf155 },

		{ localization("Pump Shotgun", true), 0x1d073a89 },
		{ localization("Pump Shotgun Mk II", true), 0x555af99a },
		{ localization("Sawed-Off Shotgun", true), 0x7846a318 },
		{ localization("Assault Shotgun", true), 0xe284c527 },
		{ localization("Bullpup Shotgun", true), 0x9d61e50f },
		{ localization("Musket", true), 0xa89cb99e },
		{ localization("Heavy Shotgun", true), 0x3aabbbaa },
		{ localization("Double Barrel Shotgun", true), 0xef951fbb },
		{ localization("Sweeper Shotgun", true), 0x12e82d3d },
		{ localization("Combat Shotgun", true), 0x5a96ba4 },

		{ localization("Assault Rifle", true), 0xbfefff6d },
		{ localization("Assault Rifle Mk II", true), 0x394f415c },
		{ localization("Carbine Rifle", true), 0x83bf0278 },
		{ localization("Carbine Rifle Mk II", true), 0xfad1f1c9 },
		{ localization("Advanced Rifle", true), 0xaf113f99 },
		{ localization("Special Carbine", true), 0xc0a3098d },
		{ localization("Special Carbine Mk II", true), 0x969c3d67 },
		{ localization("Bullpup Rifle", true), 0x7f229f94 },
		{ localization("Bullpup Rifle Mk II", true), 0x84d6fafd },
		{ localization("Compact Rifle", true), 0x624fe830 },
		{ localization("Military Rifle", true), 0x9d1f17e6 },

		{ localization("MG", true), 0x9d07f764 },
		{ localization("Combat MG", true), 0x7fd62962 },
		{ localization("Combat MG Mk II", true), 0xdbbd7280 },
		{ localization("Gusenberg Sweeper", true), 0x61012683 },

		{ localization("Sniper Rifle", true), 0x5fc3c11 },
		{ localization("Heavy Sniper", true), 0xc472fe2 },
		{ localization("Heavy Sniper Mk II", true), 0xa914799 },
		{ localization("Marksman Rifle", true), 0xc734385a },
		{ localization("Marksman Rifle Mk II", true), 0x6a6c02e0 },

		{ localization("RPG", true), 0xb1ca77b1 },
		{ localization("Grenade Launcher", true), 0xa284510b },
		{ localization("Grenade Launcher Smoke", true), 0x4dd2dc56 },
		{ localization("Minigun", true), 0x42bf8a85 },
		{ localization("Firework Launcher", true), 0x7f7497e5 },
		{ localization("Railgun", true), 0x6d544c99 },
		{ localization("Homing Launcher", true), 0x63ab0442 },
		{ localization("Compact Grenade Launcher", true), 0x781fe4a },
		{ localization("Widowmaker", true), 0xb62d1f67 },

		{ localization("Jerry Can", true), 0x34a67b97 },
		{ localization("Hazardous Jerry Can", true), 0xba536372 },
		{ localization("Parachute", true), 0xfbab5776 },
		{ localization("Fire Extinguisher", true), 0x60ec506 },
		{ localization("Digi Scanner", true), 0xfdbadced },

		{ localization("Grenade", true), 0x93e220bd },
		{ localization("BZ Gas", true), 0xa0973d5e },
		{ localization("Molotov Cocktail", true), 0x24b17070 },
		{ localization("Sticky Bomb", true), 0x2c3731d9 },
		{ localization("Proximity Mines", true), 0xab564b93 },
		{ localization("Snowballs", true), 0x787f0bb },
		{ localization("Pipe Bombs", true), 0xba45e8b8 },
		{ localization("Baseball", true), 0x23c9f95c },
		{ localization("Tear Gas", true), 0xfdbc8a50 },
		{ localization("Flare", true), 0x497facc3 },

		{ localization("Antique Cavalry Dagger", true), 0x92a27487 },
		{ localization("Baseball Bat", true), 0x958a4a8f },
		{ localization("Broken Bottle", true), 0xf9e6aa4b },
		{ localization("Crowbar", true), 0x84bd7bfd },
		{ localization("Flashlight", true), 0x8bb05fd7 },
		{ localization("Golf Club", true), 0x440e4788 },
		{ localization("Hammer", true), 0x4e875f73 },
		{ localization("Hatchet", true), 0xf9dcbf2d },
		{ localization("Brass Knuckles", true), 0xd8df3c3c },
		{ localization("Knife", true), 0x99b507ea },
		{ localization("Machete", true), 0xdd5df8d9 },
		{ localization("Switchblade", true), 0xdfe37640 },
		{ localization("Nightstick", true), 0x678b81b1 },
		{ localization("Pipe Wrench", true), 0x19044ee0 },
		{ localization("Battle Axe", true), 0xcd274149 },
		{ localization("Pool Cue", true), 0x94117305 },
		{ localization("Stone Hatchet", true), 0x3813fc08 },
	};

	scroll_struct<ExplosionTypes> g_explosions[] = {
		{ localization("Grenade", true), EXPLOSION_GRENADE },
		{ localization("Grenade Launcher", true), EXPLOSION_GRENADELAUNCHER },
		{ localization("Sticky Bomb", true), EXPLOSION_STICKYBOMB },
		{ localization("Molotov", true), EXPLOSION_MOLOTOV },
		{ localization("Rocket", true), EXPLOSION_ROCKET },
		{ localization("Tank Shell", true), EXPLOSION_TANKSHELL },
		{ localization("Hi-Octane", true), EXPLOSION_HI_OCTANE },
		{ localization("Car", true), EXPLOSION_CAR },
		{ localization("Plane", true), EXPLOSION_PLANE },
		{ localization("Petrol Pump", true), EXPLOSION_PETROL_PUMP },
		{ localization("Bike", true), EXPLOSION_BIKE },
		{ localization("Steam", true), EXPLOSION_DIR_STEAM },
		{ localization("Flame", true), EXPLOSION_DIR_FLAME },
		{ localization("Water Hydrant", true), EXPLOSION_DIR_WATER_HYDRANT },
		{ localization("Gas Fire", true), EXPLOSION_DIR_GAS_CANISTER },
		{ localization("Boat", true), EXPLOSION_BOAT },
		{ localization("Ship Destroy", true), EXPLOSION_SHIP_DESTROY },
		{ localization("Truck", true), EXPLOSION_TRUCK },
		{ localization("Bullet", true), EXPLOSION_BULLET },
		{ localization("Smoke Grenade Launcher", true), EXPLOSION_SMOKEGRENADELAUNCHER },
		{ localization("Smoke Grenade", true), EXPLOSION_SMOKEGRENADE },
		{ localization("Bz Gas", true), EXPLOSION_BZGAS },
		{ localization("Flare", true), EXPLOSION_FLARE },
		{ localization("Gas Canister", true), EXPLOSION_GAS_CANISTER },
		{ localization("Extinguisher", true), EXPLOSION_EXTINGUISHER },
		{ localization("Programmable AR", true), EXPLOSION_PROGRAMMABLEAR },
		{ localization("Train", true), EXPLOSION_TRAIN },
		{ localization("Barrel", true), EXPLOSION_BARREL },
		{ localization("Propane", true), EXPLOSION_PROPANE },
		{ localization("Blimp", true), EXPLOSION_BLIMP },
		{ localization("Flame Explode", true), EXPLOSION_DIR_FLAME_EXPLODE },
		{ localization("Tanker", true), EXPLOSION_TANKER },
		{ localization("Plane Rocket", true), EXPLOSION_PLANE_ROCKET },
		{ localization("Vehicle Bullet", true), EXPLOSION_VEHICLE_BULLET },
		{ localization("Gas Tank", true), EXPLOSION_GAS_TANK },
		{ localization("Bird Crap", true), EXPLOSION_BIRD_CRAP },
	};

	scroll_struct<float> g_gravity[] = {
		{ localization("Earth", true), 9.807f },
		{ localization("Moon", true), 1.62f },
		{ localization("Mercury", true), 3.7f },
		{ localization("Jupiter", true), 24.79f },
		{ localization("Mars", true), 3.711f },
		{ localization("Saturn", true), 10.44f },
		{ localization("Uranus/Venus", true), 8.87f },
		{ localization("Neptune", true), 11.15f },
		{ localization("Sun", true), 274.0f },
	};

	scroll_struct<int> g_opacity[] = {
		{ localization("0%", true), 0 },
		{ localization("20%", true), 51 },
		{ localization("40%", true), 102 },
		{ localization("60%", true), 153 },
		{ localization("80%", true), 204 },
		{ localization("100%", true), 255 }
	};

	scroll_struct<uint32_t> g_vehicle_weapons[] = {
		{ localization("RPG", true), 0xb1ca77b1 },
		{ localization("Snowball", true), 0x787F0BB },
		{ localization("Firework", true), 0x7f7497e5 },
		{ localization("Flare", true), 0x497FACC3 },
		{ localization("Player Laser", true), 0xeffd014b },
		{ localization("Enemy Laser", true), 0x5d6660ab },
		{ localization("Space Rocket", true), 0xf8a3939f },
		{ localization("Player Bullet", true), 0x4b139b2d },
		{ localization("Player Buzzard", true), 0x46b89c8e },
	};

	scroll_struct<std::pair<math::vector3_<float>, math::vector3_<float>>> g_acrobatics[] = {
		{ localization("Wheelie", true), { { 0.f, 0.f, 1.f }, { 0.f, 5.0f, 0.f } } },
		{ localization("Kickflip", true), { { 0.f, 0.0f, 11.5f }, { 5.f, 0.f, 0.f } } },
		{ localization("Double Kickflip", true), { { 0.f, 0.0f, 21.f }, { 10.f, 0.f, 0.f } } },
		{ localization("Quadruple Kickflip", true), {{ 0.f, 0.0f, 33.f }, { 15.f, 0.f, 0.f } } },
		{ localization("Leap", true), {{ 0.f, 0.f, 20.f }, { 0.f, 0.f, 0.f } } },
		{ localization("Slingshot", true), {{ 0.f, 0.f, 200.f }, { 0.f, 0.f, 0.f } } },
		{ localization("Backflip", true), {{ 0.f, 0.f, 15.5f }, { 0.f, 1.3f, 0.f } } },
		{ localization("Frontflip", true), {{ 0.f, 0.f, 15.5f }, { 0.f, -1.f, 0.f } } },
		{ localization("Right Jump", true), {{ 0.f, 0.f, 2.8f }, { -3.f, 0.f, 0.f } } },
		{ localization("Left Jump", true), {{ 0.f, 0.f, 2.8f }, { 3.f, 0.f, 0.f } } }
	};

	scroll_struct<math::vector3<float>> g_popular_locations[] = {
		{ localization("Diamond Casino", true), {919.94f, 50.7f, 80.90f } },
		{ localization("Los Santos Customs", true), {-365.425f, -131.809f, 37.873f } },
		{ localization("Los Santos Airport", true), {-1052.392f, -2933.508f, 13.951f } },
		{ localization("Sandy Shores Airfield", true), {1770.241f, 3266.942f, 41.620f } },
		{ localization("Eclipse Towers", true), {-807.247f, 301.868f, 86.073f } },
		{ localization("Eclipse Towers Garage (Outside)", true), {-795.46f, 308.89f, 85.71f } },
		{ localization("Eclipse Towers Roof", true), {-779.026f, 331.695f, 238.828f } },
		{ localization("Fort Zancudo", true), {-2119.877f, 3284.521f, 32.810f } },
		{ localization("Mount Chiliad", true), {498.142f, 5593.435f, 795.364f } },
		{ localization("Michael's House", true), {-803.462f, 172.808f, 72.845f } },
		{ localization("Franklin's House", true), {0.603f, 527.954f, 174.628f } },
		{ localization("Lester's House", true), {1273.727f, -1712.099f, 54.771f } },
		{ localization("Trevor's Meth Lab", true), {1393.173f, 3602.266f, 38.942f } },
		{ localization("Floyd's Apartment", true), {-1159.055f, -1520.858f, 10.633f } },
		{ localization("Prison", true), {1678.585f, 2513.168f, 45.565f } },
		{ localization("Torture Room", true), {144.672f, -2201.973f, 4.688f } },
		{ localization("Del Perro Beach", true), {-1583.278f, -1099.167f, 4.956f } },
		{ localization("Del Perro Pier", true), {-1731.210f, -1110.329f, 13.102f } },
		{ localization("Helicopter Pad", true), {-724.384f, -1443.399f, 5.001f } },
		{ localization("Maze Bank", true), {-75.858f, -817.789f, 326.174f } },
		{ localization("FIB Building", true), {135.786f, -749.233f, 258.152f } },
		{ localization("IAA Office", true), {121.282f, -622.149f, 206.047f } },
		{ localization("Blaine County Bank", true), {-108.245f, 6466.301f, 31.627f } },
		{ localization("Pacific Standard Vault", true), {256.786f, 226.157f, 101.876f } },
		{ localization("Humane Labs", true), {3616.195f, 3738.724f, 28.690f } },
		{ localization("Humane Labs Tunnel", true), {3524.949f, 3708.167f, 20.992f } },
		{ localization("Playboy Mansion", true), {-1461.834f, 179.259f, 54.752f } },
		{ localization("Mors Mutual Insurance", true), {-232.084f, -1163.830f, 22.948f } },
		{ localization("Impound Lot", true), {401.057f, -1631.766f, 29.293f } },
		{ localization("Police Station", true), {441.259f, -983.160f, 30.690f } },
		{ localization("Underwater UFO", true), {763.656f, 7381.180f, -110.135f } },
		{ localization("Vinewood Sign", true), {741.941f, 1198.555f, 326.344f } },
		{ localization("Waterfall", true), {-597.9525f, 4475.2910f, 25.6890f } },
		{ localization("Island", true), {20.968f, 7636.292f, 15.943f } },
		{ localization("Bank Vault", true), { 255.5819f, 217.6896f, 101.6834f }}
	};

	scroll_struct<uint32_t> g_object_model_small[] = {
		{ localization("Alarm", true), 0x9E5FFFCB },
		{ localization("Backpack", true), 0x47B7DAED },
		{ localization("Barbell", true), 0xE2FBA8D8 },
		{ localization("Basketball", true), 0x6DB9599A },
		{ localization("Beachball", true), 0x81ECE1F },
		{ localization("Bear 1", true), 0x772114C9 },
		{ localization("Bear 2", true), 0x3CF34F26 },
		{ localization("Bigfoot Mask", true), 0xC9751EF7 },
		{ localization("Bong", true), 0xF0A61994 },
		{ localization("Campfire", true), 0xC079B265 },
		{ localization("Candle", true), 0x203011A1 },
		{ localization("Dildo", true), 0xE6CB661E },
		{ localization("Dog Cage", true), 0x16A39A90 },
		{ localization("Egg", true), 0x6B795EBC },
		{ localization("EMP", true), 0x3794ACC9 },
		{ localization("Engine", true), 0xDD75614 },
		{ localization("Fish", true), 0xCE3D7AA0 },
		{ localization("Gold", true), 0xF046EA37 },
		{ localization("Guitar 1", true), 0xD5C0BC07 },
		{ localization("Guitar 2", true), 0xA4E7E0A7 },
		{ localization("Hotdog", true), 0x98EE1ACD },
		{ localization("Katana", true), 0xE2BA016F },
		{ localization("Lawnmower", true), 0x1AB39621 },
		{ localization("Leafblower", true), 0x5F989485 },
		{ localization("Minigun", true), 0xC89630B8 },
		{ localization("Missile", true), 0xB2274905 },
		{ localization("Parachute", true), 0x34DCF0A3 },
		{ localization("Pumpkin", true), 0x83C07621 },
		{ localization("Safe", true), 0x40F52369 },
		{ localization("Saxophone", true), 0x1212FE11 },
		{ localization("Scuba Tank", true), 0x18B8F776 },
		{ localization("Shield", true), 0x44083A8F },
		{ localization("Shit", true), 0x84898EFE },
		{ localization("Soccer Ball", true), 0xD541462D },
		{ localization("Toilet", true), 0x6F9939C7 },
		{ localization("Traffic Cone", true), 0xE0264F5D },
		{ localization("TV", true), 0x5C9F1C35 },
		{ localization("Volleyball", true), 0xC79A987E },
		{ localization("Weed", true), 0x1AFA6A0A },
	};

	scroll_struct<uint32_t> g_object_model_medium[] = {
		{ localization("Anti-Aircraft", true), 0x98D3236B },
		{ localization("Arcade", true), 0xA50DDDD0 },
		{ localization("Bed", true), 0xB374CC1F },
		{ localization("Bench", true), 0x6BA514AC },
		{ localization("Blast Fence", true), 0xB4978950 },
		{ localization("Block", true), 0xC3F13FCC },
		{ localization("Bumper Car", true), 0xFB631122 },
		{ localization("Cheetah", true), 0x37D80B0E },
		{ localization("Dinghy", true), 0x282D6851 },
		{ localization("Entity XF", true), 0xB155FD87 },
		{ localization("Ferris Car", true), 0x1AFA509F },
		{ localization("Helicopter", true), 0x8E8C7A5B },
		{ localization("JB700", true), 0x72F54E90 },
		{ localization("Jetski Ramp", true), 0xBF8918DE },
		{ localization("Log", true), 0xACD6D1AB },
		{ localization("Mannequin", true), 0x7FFBC1E2 },
		{ localization("Orange Sphere", true), 0x8DA1C0E },
		{ localization("Propeller", true), 0x5D20643D },
		{ localization("Ramp 1", true), 0xB157C9E4 },
		{ localization("Ramp 2", true), 0xF4F1511E },
		{ localization("Ramp 3", true), 0x93948E5E },
		{ localization("Repair", true), 0xE6FA7770 },
		{ localization("Sand Block", true), 0xF724026D },
		{ localization("Sofa", true), 0x5EF5520E },
		{ localization("Stairs", true), 0x757C28D },
		{ localization("Umbrella", true), 0xDCA9A809 },
		{ localization("Xmas Tree", true), 0xE3BA450 },
	};

	scroll_struct<uint32_t> g_object_model_large[] = {
		{ localization("Asteroid", true), 0xDF9841D7 },
		{ localization("Barge 1", true), 0x9C762726 },
		{ localization("Barge 2", true), 0x8AF58425 },
		{ localization("Cablecar", true), 0xD44295DD },
		{ localization("Crane", true), 0x7D10B85C },
		{ localization("Crane Cab", true), 0x3673E396 },
		{ localization("Ferris Wheel", true), 0xC42C019A },
		{ localization("Halfpipe", true), 0xF66F582F },
		{ localization("Jet", true), 0xC2BC19CD },
		{ localization("Lava", true), 0xD733DF },
		{ localization("Radar", true), 0x8973A868 },
		{ localization("Large Tarp", true), 0x6FA720A4 },
		{ localization("Tree", true), 0xEDF5CD3C },
		{ localization("Tugboat", true), 0xF20B1BDD },
		{ localization("UFO", true), 0xB467C540 },
		{ localization("Windmill", true), 0x745F3383 },
		{ localization("Xmas Tree", true), 0x7121AC4 },
	};

	scroll_struct<uint32_t> g_object_model_flags[] = {
		{ localization("Canada", true), joaat("prop_flag_canada") },
		{ localization("Europe", true), joaat("prop_flag_eu") },
		{ localization("France", true), joaat("prop_flag_france") },
		{ localization("Germany", true), joaat("prop_flag_german") },
		{ localization("Ireland", true), joaat("prop_flag_ireland") },
		{ localization("Japan", true), joaat("prop_flag_japan") },
		{ localization("City of Los Santos", true), joaat("prop_flag_ls") },
		{ localization("Los Santos Fire Department", true), joaat("prop_flag_lsfd") },
		{ localization("Los Santos Services", true), joaat("prop_flag_lsservices") },
		{ localization("Mexico", true), joaat("prop_flag_mexico") },
		{ localization("Russia", true), joaat("prop_flag_russia") },
		{ localization("San Andreas Republic", true), joaat("prop_flag_sa") },
		{ localization("San Andreas Police Department", true), joaat("prop_flag_sapd") },
		{ localization("Scotland", true), joaat("prop_flag_scotland") },
		{ localization("Los Santos County Sheriff", true), joaat("prop_flag_sheriff") },
		{ localization("United Kingdom", true), joaat("prop_flag_uk") },
		{ localization("United States", true), joaat("prop_flag_us") },
	};

	scroll_struct<float> g_precisions[] = {
		{ localization(".0001", false), .0001f },
		{ localization(".001", false), .001f },
		{ localization(".01", false), .01f },
		{ localization(".1", false), .1f },
		{ localization("1", true), 1.f },
		{ localization("2", true), 2.f },
		{ localization("5", true), 5.f },
		{ localization("10", true), 10.f },
		{ localization("50", true), 50.f },
		{ localization("100", true), 100.f }
	};

	scroll_struct<std::pair<const char*, const char*>> g_sounds[] = {
		{ localization("Alien", true), { "SPAWN", "BARRY_01_SOUNDSET" } },
		{ localization("Whistle", true), { "Franklin_Whistle_For_Chop", "SPEECH_RELATED_SOUNDS" } },
		{ localization("EMP", true), { "EMP_Vehicle_Hum", "DLC_HEIST_BIOLAB_DELIVER_EMP_SOUNDS" } },
		{ localization("Helicopter", true), { "Helicopter_Wind", "BASEJUMPS_SOUNDS" } },
		{ localization("Scan", true), { "SCAN", "EPSILONISM_04_SOUNDSET" } },
		{ localization("Leafblower", true), { "GARDENING_LEAFBLOWER_ANIM_TRIGGERED", "" } },
		{ localization("Unlock", true), { "Bar_Unlock_And_Raise", "DLC_IND_ROLLERCOASTER_SOUNDS" } },
		{ localization("Brakes", true), { "MOD_SHOP_BRAKES_ONESHOT", "" } },

		{ localization("Carwash", true), { "SPRAY", "CARWASH_SOUNDS" } },
		{ localization("Carwash 2", true), { "SPRAY_CAR", "CARWASH_SOUNDS" } },
		{ localization("Carwash 3", true), { "DRYER", "CARWASH_SOUNDS" } },

		{ localization("Keycard", true), { "Keycard_Success", "DLC_HEISTS_BIOLAB_FINALE_SOUNDS" } },
		{ localization("Keycard 2", true), { "Keycard_Fail", "DLC_HEISTS_BIOLAB_FINALE_SOUNDS" } },

		{ localization("Ringtone", true), { "Remote_Ring", "Phone_SoundSet_Michael" } },
		{ localization("Ringtone 2", true), { "PED_PHONE_DIAL_01", "" } },

		{ localization("Beep", true), { "Crate_Beeps", "MP_CRATE_DROP_SOUNDS" } },
		{ localization("Beep 2", true), { "Crate_Collect", "MP_CRATE_DROP_SOUNDS" } },
		{ localization("Endless Beep", true), { "CONTINUAL_BEEP", "EPSILONISM_04_SOUNDSET" } },
		{ localization("Short Beep", true), { "IDLE_BEEP", "EPSILONISM_04_SOUNDSET" } },
		{ localization("Long Beep", true), { "Beep_Green", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ localization("Solo Fast Beep", true), { "Beep_Red", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ localization("Confirm Beep", true), { "CONFIRM_BEEP", "HUD_MINI_GAME_SOUNDSET" } },

		{ localization("5s Timer", true), { "5_Second_Timer", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ localization("5s Timer 2", true), { "MP_5_SECOND_TIMER", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("Idle Timer", true), { "MP_IDLE_TIMER", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("Out of Bounds Timer", true), { "Out_Of_Bounds_Timer", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ localization("Timer Stop", true), { "TIMER_STOP", "HUD_MINI_GAME_SOUNDSET" } },

		{ localization("Pickup", true), { "PICK_UP", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("Pickup 2", true), { "PICK_UP_SOUND", "HUD_FRONTEND_CUSTOM_SOUNDSET" } },
		{ localization("Pickup 3", true), { "PICKUP_WEAPON_SMOKEGRENADE", "HUD_FRONTEND_WEAPONS_PICKUPS_SOUNDSET" } },

		{ localization("Silence", true), { "3_2_1_NON_RACE", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("Silence 2", true), { "Airhorn", "DLC_TG_Running_Back_Sounds" } },

		{ localization("Screen Flash", true), { "ScreenFlash", "MissionFailedSounds" } },
		{ localization("Screen Flash 2", true), { "ScreenFlash", "WastedSounds" } },

		{ localization("Click", true), { "Click", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ localization("Click Fail", true), { "Click_Fail", "WEB_NAVIGATION_SOUNDS_PHONE" } },
		{ localization("Click Special", true), { "Click_Special", "WEB_NAVIGATION_SOUNDS_PHONE" } },

		{ localization("Nav Arrow Ahead", true), { "Nav_Arrow_Ahead", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ localization("Nav Arrow Left", true), { "Nav_Arrow_Left", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ localization("Nav Arrow Right", true), { "Nav_Arrow_Right", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },

		{ localization("Checkpoint Missed", true), { "CHECKPOINT_MISSED", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("Checkpoint Ahead", true), { "CHECKPOINT_AHEAD", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("Checkpoint Perfect", true), { "CHECKPOINT_PERFECT", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("Checkpoint Under Bridge", true), { "CHECKPOINT_UNDER_THE_BRIDGE", "HUD_MINI_GAME_SOUNDSET" } },

		{ localization("Menu Select", true), { "Apt_Style_Purchase", "DLC_APT_Apartment_SoundSet" } },
		{ localization("Menu Select 2", true), { "SELECT", "HUD_MINI_GAME_SOUNDSET" } },

		{ localization("Hack Failed", true), { "Hack_Failed", "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS" } },
		{ localization("Hack Success", true), { "Hack_Success", "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS" } },

		{ localization("Pin Bad", true), { "Pin_Bad", "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS" } },
		{ localization("Pin Button", true), { "PIN_BUTTON", "ATM_SOUNDS" } },
		{ localization("Pin Good", true), { "Pin_Good", "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS" } },

		{ localization("Tennis Match Point", true), { "TENNIS_MATCH_POINT", "HUD_AWARDS" } },
		{ localization("Tennis Point Won", true), { "TENNIS_POINT_WON", "HUD_AWARDS" } },

		{ localization("Start Squelch", true), { "Start_Squelch", "CB_RADIO_SFX" } },
		{ localization("End Squelch", true), { "End_Squelch", "CB_RADIO_SFX" } },

		{ localization("Garage Door Open", true), { "RAMP_UP", "TRUCK_RAMP_DOWN" } },
		{ localization("1st Person Transition", true), { "1st_Person_Transition", "PLAYER_SWITCH_CUSTOM_SOUNDSET" } },
		{ localization("Emphasis", true), { "3_2_1", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("5s Warning", true), { "5_SEC_WARNING", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("Notification", true), { "ATM_WINDOW", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("Challenge Unlocked", true), { "CHALLENGE_UNLOCKED", "HUD_AWARDS" } },
		{ localization("Mission Success", true), { "BASE_JUMP_PASSED", "HUD_AWARDS" } },
		{ localization("Wasted", true), { "Bed", "WastedSounds" } },
		{ localization("Bus Pickup", true), { "Bus_Schedule_Pickup", "DLC_PRISON_BREAK_HEIST_SOUNDS" } },
		{ localization("Taken Photo", true), { "Camera_Shoot", "Phone_Soundset_Franklin" } },
		{ localization("Switching Characters", true), { "CHARACTER_SELECT", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("Close Window", true), { "CLOSE_WINDOW", "LESTER1A_SOUNDS" } },
		{ localization("Crash", true), { "Crash", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ localization("Delete", true), { "DELETE", "HUD_DEATHMATCH_SOUNDSET" } },
		{ localization("Truck Rev", true), { "DiggerRevOneShot", "BulldozerDefault" } },
		{ localization("Drill Pin Break", true), { "Drill_Pin_Break", "DLC_HEIST_FLEECA_SOUNDSET" } },
		{ localization("Edit", true), { "EDIT", "HUD_DEATHMATCH_SOUNDSET" } },
		{ localization("Error", true), { "ERROR", "HUD_AMMO_SHOP_SOUNDSET" } },
		{ localization("Failure", true), { "Failure", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ localization("Falling Crates", true), { "Falling_Crates", "EXILE_1" } },
		{ localization("Car Breakdown", true), { "FAMILY_1_CAR_BREAKDOWN", "FAMILY1_BOAT" } },
		{ localization("First Place", true), { "FIRST_PLACE", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("Flight School Passed", true), { "FLIGHT_SCHOOL_LESSON_PASSED", "HUD_AWARDS" } },
		{ localization("Focus In", true), { "FocusIn", "HintCamSounds" } },
		{ localization("Go", true), { "GO", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("Goal", true), { "Goal", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ localization("Grab Parachute", true), { "Grab_Parachute", "BASEJUMPS_SOUNDS" } },
		{ localization("Hang Up", true), { "Hang_Up", "Phone_SoundSet_Michael" } },
		{ localization("Highlight Error", true), { "Highlight_Error", "DLC_HEIST_PLANNING_BOARD_SOUNDS" } },
		{ localization("Hit", true), { "Hit", "RESPAWN_SOUNDSET" } },
		{ localization("Hit 2", true), { "Hit_1", "LONG_PLAYER_SWITCH_SOUNDS" } },
		{ localization("Hit Out", true), { "Hit_Out", "PLAYER_SWITCH_CUSTOM_SOUNDSET" } },
		{ localization("Cash Counter Complete", true), { "LOCAL_PLYR_CASH_COUNTER_COMPLETE", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ localization("Lose Match", true), { "LOOSE_MATCH", "HUD_MINI_GAME_SOUNDSET" } },
		{ localization("Loser", true), { "LOSER", "HUD_AWARDS" } },
		{ localization("Menu Accept", true), { "Menu_Accept", "Phone_SoundSet_Default" } },
		{ localization("Mission Pass Notify", true), { "Mission_Pass_Notify", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ localization("Award", true), { "MP_AWARD", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("Idle Kick", true), { "MP_IDLE_KICK", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("Rank Up", true), { "MP_RANK_UP", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("Wave Complete", true), { "MP_WAVE_COMPLETE", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ localization("On", true), { "ON", "NOIR_FILTER_SOUNDS" } },
		{ localization("On Call Player Join", true), { "On_Call_Player_Join", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ localization("Open Window", true), { "OPEN_WINDOW", "LESTER1A_SOUNDS" } },
		{ localization("Other Text", true), { "OTHER_TEXT", "HUD_AWARDS" } },
		{ localization("Player Collect", true), { "Player_Collect", "DLC_PILOT_MP_HUD_SOUNDS" } },
		{ localization("Power Down", true), { "Power_Down", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ localization("Pre Screen Stinger", true), { "Pre_Screen_Stinger", "DLC_HEISTS_FAILED_SCREEN_SOUNDS" } },
		{ localization("Property Purchase", true), { "PROPERTY_PURCHASE", "HUD_AWARDS" } },
		{ localization("Money Lost", true), { "PS2A_MONEY_LOST", "PALETO_SCORE_2A_BANK_SS" } },
		{ localization("Put Away", true), { "Put_Away", "Phone_SoundSet_Michael" } },
		{ localization("Round Ending", true), { "ROUND_ENDING_STINGER_CUSTOM", "CELEBRATION_SOUNDSET" } },
		{ localization("Heartbeat", true), { "Short_Transition_In", "PLAYER_SWITCH_CUSTOM_SOUNDSET" } },
		{ localization("Bomb Loading", true), { "STUN_COLLECT", "MINUTE_MAN_01_SOUNDSET" } },
	};

	scroll_struct<int> g_markers[] = {
		{ localization("Upside Down Cone", true), 0 },
		{ localization("Vertical Cylinder", true), 0 },
		{ localization("Thick Chevron Up", true), 0 },
		{ localization("Thin Chevron Up", true), 0 },
		{ localization("Checkered Flag Rect", true), 0 },
		{ localization("Checkered Flag Circle", true), 0 },
		{ localization("Verticle Circle", true), 0 },
		{ localization("Plane Model", true), 0 },
		{ localization("Lost MC Transparent", true), 0 },
		{ localization("Lost MC", true), 0 },
		{ localization("Number 0", true), 0 },
		{ localization("Number 1", true), 0 },
		{ localization("Number 2", true), 0 },
		{ localization("Number 3", true), 0 },
		{ localization("Number 4", true), 0 },
		{ localization("Number 5", true), 0 },
		{ localization("Number 6", true), 0 },
		{ localization("Number 7", true), 0 },
		{ localization("Number 8", true), 0 },
		{ localization("Number 9", true), 0 },
		{ localization("Chevron Up X1", true), 0 },
		{ localization("Chevron Up X2", true), 0 },
		{ localization("Chevron Up X3", true), 0 },
		{ localization("Horizontal Circle Fat", true), 0 },
		{ localization("Replay Icon", true), 0 },
		{ localization("Horizontal Circle Skinny", true), 0 },
		{ localization("Horizontal Circle Skinny Arrow", true), 0 },
		{ localization("Horizontal Split Arrow Circle", true), 0 },
		{ localization("Debug Sphere", true), 0 },
		{ localization("Dollar Sign", true), 0 },
		{ localization("Horizontal Bars", true), 0 },
		{ localization("Wolf Head", true), 0 },
		{ localization("Question Mark", true), 0 },
		{ localization("Plane Symbol", true), 0 },
		{ localization("Helicopter Symbol", true), 0 },
		{ localization("Boat Symbol", true), 0 },
		{ localization("Car Symbol", true), 0 },
		{ localization("Motorcycle Symbol", true), 0 },
		{ localization("Bike Symbol", true), 0 },
		{ localization("Truck Symbol", true), 0 },
		{ localization("Parachute Symbol", true), 0 },
		{ localization("Jetpack Symbol", true), 0 },
		{ localization("Sawblade Symbol", true), 0 },
	};
}